# Conclusion

In conclusion, we observed several distinct patterns in how people perceive movies. Overall, most people tend to give relatively positive ratings. Ratings given to different genres are mostly similar, regardless of whether movies evoke more positive or negative emotions. However, people do tend to rate genres higher if they watch them more frequently. Additionally, we have observed positive correlations for certain genre selections as well as negative correlations for others. For example, selection of Adventure and Action as well as Animation and Children have positive correlations; selection of Romance and Action as well as Adventure and Drama have negative correlations.
However, one limitation of our project is related to sentiment analysis. The tags people assigned movies might not always accurately reflect their emotional sentiments, and the package "syuzhet" may not capture the full scope of sentiment nuances. Going forward, we would be interested in finding datasets specifically focused on sentiment-related questions, which can provide more insights. 